name: App Settings Variable Substitution

on:
  workflow_call:
    inputs:
      project_directory:
        required: true
        type: string

jobs:
  substitute:
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ${{ inputs.project_directory }}/publish

      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{ inputs.project_directory }}/publish/appsettings.json'
        env:
          ConnectionStrings.DefaultConnection: ${{ secrets.DB_CONN_STRING }}
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ${{ env.project_directory }}/publish