name: .NET Core Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      Project_Directory: ./School-Portal.BE/School-Portal.API  

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: List directory contents
      run: ls -R

    - name: Restore dependencies
      run: dotnet restore
      working-directory: $env:Project_Directory

    - name: Build
      run: dotnet build --no-restore
      working-directory: $env:Project_Directory

    - name: Run tests
      run: dotnet test --no-restore --verbosity normal
      working-directory: $env:Project_Directory
      
    - name: Publish
      run: dotnet publish --configuration Release --output ./publish
      working-directory: $env:Project_Directory

    - name: Delete all files in the directory
      uses: StephanThierry/ftp-delete-action@v2.1
      with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          remoteFiles: /wwwroot/*
          ignoreSSL: 1
 
    - name: FTP Deploy 
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }} 
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: 21  
        local-dir: $env:Project_Directory/publish/
        server-dir: /wwwroot/
        state-name: .ftp-deploy-sync-state.json
        dangerous-clean-slate: true